[package]
name = "compiler-llvm-context"
version = "1.3.2"
authors = [
    "Oleksandr Zarudnyi <a.zarudnyy@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The zkEVM compilers shared LLVM context"

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
semver = "1.0"
itertools = "0.10"
serde = { version = "1.0", "features" = [ "derive" ] }
regex = "1.8"
once_cell = "1.17"
num = "0.4"
hex = "0.4"
sha2 = "0.10"
sha3 = "0.10"
md5 = "0.7"

zkevm_opcode_defs = { git = "https://github.com/matter-labs/era-zkevm_opcode_defs", branch = "v1.3.2" }
zkevm-assembly = { git = "https://github.com/matter-labs/era-zkEVM-assembly", branch = "v1.3.2" }
compiler-common = { git = "https://github.com/matter-labs/era-compiler-common", branch = "main" }

[dependencies.inkwell]
git = "https://github.com/matter-labs-forks/inkwell"
branch = "llvm-15"
default-features = false
features = ["llvm15-0", "no-libffi-linking", "target-syncvm"]
